# Generated by Django 3.1.7 on 2021-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshort',
            name='id',
        ),
        migrations.AddField(
            model_name='urlshort',
            name='sid',
            field=models.CharField(default='dfd', max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
